service: typescript-serverless-boilerplate

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    restApiId: ${cf:api-${self:provider.stage}.ApiGatewayRestApiId}
    restApiRootResourceId: ${cf:api-${self:provider.stage}.ApiGatewayRestApiResourceId}

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!node_modules/**/src/**'
    - '!src/**'
    - '!scripts/**'
    - '!dist/**'
    - '!layers/**'
    - '!database/**'
    - '!schema.prisma'
    - '!tsconfig.json'
    - '!tslint.json'
    - 'prisma/**'
    - 'node_modules/.prisma/**'

functions:
  hello:
    handler: dist/endpoints/hello/handler.hello
    package:
      patterns:
        - 'dist/endpoints/hello/handler.js'
    events:
      - http:
          path: /hello/world
          method: get
